[package]
name = "nctl"
version = "0.3.2"
authors = ["Éric BURGHARD <ericd@itsufficient.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
argh = "0.1"
ureq = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
